import type { Metadata } from 'next';
import { Mochiy_Pop_One, Inter } from 'next/font/google';

import { HeroUIProvider } from './HeroUIProvider';
import './globals.css';

const mochiyPopOne = Mochiy_Pop_One({
  variable: '--font-mochiy-pop-one',
  weight: '400',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${mochiyPopOne.variable} ${inter.variable} antialiased custom-theme`}
      >
        <HeroUIProvider>{children}</HeroUIProvider>
      </body>
    </html>
  );
}
